### ISSUE TITLE
It's possible for the scheduler to crash due to GC Overhead Limit

### ISSUE THREAD

**Issue by BenWhitehead** [mesosphere/cassandra-mesos#99]
```
Exception in thread "Thread-96988" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.AbstractStringBuilder.<init>(Unknown Source)
	at java.lang.StringBuilder.<init>(Unknown Source)
	at ch.qos.logback.classic.pattern.TargetLengthBasedClassNameAbbreviator.abbreviate(TargetLengthBasedClassNameAbbreviator.java:28)
	at ch.qos.logback.classic.pattern.NamedConverter.convert(NamedConverter.java:53)
	at ch.qos.logback.classic.pattern.NamedConverter.convert(NamedConverter.java:18)
	at ch.qos.logback.core.pattern.FormattingConverter.write(FormattingConverter.java:37)
	at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters(PatternLayoutBase.java:119)
	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:149)
	at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:39)
	at ch.qos.logback.core.encoder.LayoutWrappingEncoder.doEncode(LayoutWrappingEncoder.java:134)
	at ch.qos.logback.core.OutputStreamAppender.writeOut(OutputStreamAppender.java:194)
	at ch.qos.logback.core.FileAppender.writeOut(FileAppender.java:209)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:219)
	at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(RollingFileAppender.java:182)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:103)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:88)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:273)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:260)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:442)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396)
	at ch.qos.logback.classic.Logger.info(Logger.java:620)
	at io.mesosphere.mesos.frameworks.cassandra.scheduler.CassandraCluster._getTasksForOffer(CassandraCluster.java:1245)
	at io.mesosphere.mesos.frameworks.cassandra.scheduler.CassandraCluster.getTasksForOffer(CassandraCluster.java:342)
	at io.mesosphere.mesos.frameworks.cassandra.scheduler.CassandraScheduler.evaluateOffer(CassandraScheduler.java:270)
	at io.mesosphere.mesos.frameworks.cassandra.scheduler.CassandraScheduler.resourceOffers(CassandraScheduler.java:93)
```

**Comment by snazy** [comment]
Did it occur while running a big cluster?

**Comment by BenWhitehead** [comment]
Yes it happened due to the trace logging of resource offers when running as the only framework on a 100 nodes cluster.

**Comment by snazy** [comment]
Yea - debug + trace logging might be one reason. Another reason might be (de)construction of the big arrays for nodes and health checks (`CassandraCluster.recordHealthCheck`).

As a temporary workaround maybe just increase the scheduler's heap size. There might be big pressure on new-gen caused by that object constructions. These should fit into new-gen (which might not be the case if the heap's just too small).

It might be worth to consider adding one object per node to {{State}} so only one small object gets updated during health-check response processing instead of a big one. That happens 10 times per second on a 100 node cluster (if health-check interval is 10 seconds).

Another thing worth to consider is to lower the health-check interval for nodes that are not starting or stopping. For example one health-check once per minute.

**Comment by BenWhitehead** [comment]
Makes sense, I've only seen this happen once and ultimately the framework was able to be restarted by marathon and recover so it hasn't become high priority yet.

**Comment by snazy** [comment]
Well, then probably just adjust the heap size :)
